spring:
  rabbitmq:
      addresses: 119.61.26.163:5672
      username: demo
      password: 123456
      publisher-confirms: true
      virtual-host: /
  
  
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/xiaohua?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 900205
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

      
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8081
  connection-timeout: 5000ms
  servlet:
    context-path: /
xxl: 
  job:
    admin:
      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://127.0.0.1:8080/xxl-job-admin
    ### xxl-job executor address
    executor:
      appname: joke
      ip: 127.0.0.1
      port: 9987
      ### xxl-job log path
      logpath: /data/applogs/xxl-job/jobhandler
      ### xxl-job log retention days
      logretentiondays: -1
    ### xxl-job, access token
    accessToken:
#mybatis
mybatis: 
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.example.demo.modules.user
  configuration:
    map-underscore-to-camel-case: true
#  data:
#    elasticsearch:
#      cluster-name: my-es-02
#      cluster-nodes: 10.10.1.60:9300
#      local: false
#      repositories:
#        enable: true 
  
  redis:
      open: true  # 是否开启redis缓存  true开启   false关闭
      database: 0
      host: 10.10.1.60
      port: 6379
      password: nldwy    # 密码（默认为空）
      timeout: 6000ms  # 连接超时时长（毫秒）
      jedis:
        pool:
          max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1ms      # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 5       # 连接池中的最小空闲连接  
 
  
    

        